[[overview]]
== Overview

This is the official low-level Python client for {es}. Its goal is to provide 
common ground for all {es}-related code in Python. For this reason, the client 
is designed to be unopinionated and extendable. Full documentation is available 
on https://github.com/infinilabs/easysearch-py[Read the Docs].


[discrete]
=== Compatibility

Current development happens in the master branch.

The library is compatible with Easysearch 1.x and 2.x. You should
**have to use a matching major version**:

For **Easysearch 2.x**, use version 2.x of the library.

For **Easysearch 1.x**, use version 1.x of the library.

The recommended way to set your requirements in your `setup.py` or
`requirements.txt` is::

    # Easysearch 2.x
    easysearch>=2,<3

    # Easysearch 1.x
    easysearch>=1,<2

If you have a need to have multiple versions installed at the same time older
versions may be released with different package names if needed.


[discrete]
=== Example use

Simple use-case:

[source,python]
------------------------------------
>>> from datetime import datetime
>>> from easysearch import Easysearch

# By default we connect to localhost:9200
>>> es = Easysearch()

# Datetimes will be serialized...
>>> es.index(index="my-index-000001", doc_type="test-type", id=42, body={"any": "data", "timestamp": datetime.now()})
{'_id': '42', '_index': 'my-index-000001', '_type': 'test-type', '_version': 1, 'ok': True}

# ...but not deserialized
>>> es.get(index="my-index-000001", doc_type="test-type", id=42)['_source']
{'any': 'data', 'timestamp': '2013-05-12T19:45:31.804229'}
------------------------------------

[NOTE]
All the API calls map the raw REST API as closely as possible, including
the distinction between required and optional arguments to the calls. This
means that the code makes distinction between positional and keyword arguments;
we, however, recommend that people use keyword arguments for all calls for
consistency and safety.


[discrete]
=== Features

The client's features include:

* Translating basic Python data types to and from JSON

* Configurable automatic discovery of cluster nodes

* Persistent connections

* Load balancing (with pluggable selection strategy) across all available nodes

* Failed connection penalization (time based - failed connections won't be
  retried until a timeout is reached)

* Thread safety

* Pluggable architecture

The client also contains a convenient set of
https://github.com/infinilabs/easysearch-py/en/master/helpers.html[helpers] for
some of the more engaging tasks like bulk indexing and reindexing.





[discrete]
=== License

Licensed to INFINI Labs under one or more contributor
license agreements. See the NOTICE file distributed with
this work for additional information regarding copyright
ownership. INFINI Labs licenses this file to you under
the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
